version: "3.8"

services:
  geth-1:
    image: ethereum/client-go:v1.13.4
    entrypoint: /geth-init.sh
    command:
      - geth
      - --networkid=28256
      - --state.scheme=path
      - --verbosity=3
      - --datadir=/execution-data
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,engine,net,eth,web3,debug
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,engine,net,eth,web3,debug
      - --ws.origins=*
      - --allow-insecure-unlock
      - --nat=extip:127.0.0.1
      - --verbosity=3
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/output/jwt/jwtsecret
      - --syncmode=full
      - --rpc.allow-unprotected-txs
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=9001
    volumes:
      - ./execution-data:/execution-data
      - ./output:/output
      - ./entrypoint/geth-init.sh:/geth-init.sh
    ports:
      - "8545:8545" # Map HTTP RPC port from container to host
      - "8546:8546" # Map WebSocket RPC port from container to host
      - "8551:8551" # Map Auth RPC port from container to host
      - "9001:9001" # Map metrics port from container to host
    restart: unless-stopped

  lighthouse-beacon-1:
    image: sigp/lighthouse:v4.5.0
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/output/custom_config_data
      - --disable-enr-auto-update
      - --enr-address=127.0.0.1
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --listen-address=0.0.0.0
      - --port=9000
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --http-allow-sync-stalled
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --execution-endpoints=http://geth-1:8551
      - --jwt-secrets=/output/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --subscribe-all-subnets
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
    volumes:
      - ./consensus-data:/consensus-data # Maps the local 'consensus-data' directory to the container's 'datadir'
      - ./output:/output # Maps the local 'output' directory to the container
    ports:
      - "9000:9000/udp" # ENR UDP port mapping
      - "9000:9000/tcp" # ENR TCP port mapping
      - "4000:4000" # HTTP port mapping
      - "5054:5054" # Metrics port mapping
    depends_on:
      - geth-1
    restart: unless-stopped

  lighthouse-validator-1:
    image: sigp/lighthouse:v4.5.0
    command:
      - lighthouse
      - validator_client
      - --debug-level=info
      - --testnet-dir=/output/custom_config_data
      - --validators-dir=/validator-keys/node-0-keystores/keys
      - --secrets-dir=/validator-keys/node-0-keystores/secrets
      - --init-slashing-protection
      - --http
      - --unencrypted-http-transport
      - --http-address=0.0.0.0
      - --http-port=5042
      - --beacon-nodes=http://lighthouse-beacon-1:4000
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5064
    volumes:
      - ./output:/output
      - ./validator-keys:/validator-keys
    ports:
      - "5042:5042" # Expose HTTP port for the validator client
      - "5064:5064" # Expose metrics port for the validator client
    depends_on:
      - lighthouse-beacon-1
    restart: unless-stopped

