version: "3.8"

services:
  geth-3:
    image: ethereum/client-go:v1.13.4
    entrypoint: /geth-init.sh
    command:
      - geth
      - --networkid=28256
      - --state.scheme=path
      - --verbosity=3
      - --datadir=/execution-data
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,engine,net,eth,web3,debug
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,engine,net,eth,web3,debug
      - --ws.origins=*
      - --allow-insecure-unlock
      - --nat=extip:127.0.0.1
      - --verbosity=3
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/output/jwt/jwtsecret
      - --syncmode=full
      - --rpc.allow-unprotected-txs
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=9001
      - --bootnodes=enode://9fd02119204fb6d134bf8ce2e74192a3d1fee129bd2b5ac29ad0ba1d77b3c3a84507665896eae6529fdf9d5b5b56cfc00fc6978e78b9e9c35e562e6431ab0ab0@172.16.16.7:30303
    volumes:
      - ./execution-data-3:/execution-data
      - ./data:/output
      - ./entrypoint/geth-init.sh:/geth-init.sh
    ports:
      - "10545:8545" # Map HTTP RPC port from container to host
      - "10546:8546" # Map WebSocket RPC port from container to host
      - "10551:8551" # Map Auth RPC port from container to host
      - "11001:9001" # Map metrics port from container to host
    restart: unless-stopped

  lighthouse-beacon-3:
    image: sigp/lighthouse:v4.5.0
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/output/custom_config_data
      - --disable-enr-auto-update
      - --enr-address=172.18.0.3
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --listen-address=0.0.0.0
      - --port=9000
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --http-allow-sync-stalled
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --execution-endpoints=http://172.20.0.2:8551
      - --jwt-secrets=/output/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --subscribe-all-subnets
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --boot-nodes=enr:-MS4QG-yG0x-xmwZctmYKLIVWcaPEwdCdL5JVpcG2rm4rzKUGcPuSB2WNXcbUX2IbnlNgIgV9qust-vj59xeef3tMNsBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAz7GdIQAAAOP__________gmlkgnY0gmlwhKwQEAmEcXVpY4IjKYlzZWNwMjU2azGhApktWymkhxLaKzA1uPjgyLgpFcg6dqMfAn_8sJ7HqEcQiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
      - --trusted-peers=16Uiu2HAm5jcUGTBezytPibfHbsE5tckP2pJCF416wBKzyFM2VSvT
    volumes:
      - ./consensus-data-3:/consensus-data # Maps the local 'consensus-data' directory to the container's 'datadir'
      - ./data:/output # Maps the local 'output' directory to the container
    ports:
      - "11000:9000/udp" # ENR UDP port mapping
      - "11000:9000/tcp" # ENR TCP port mapping
      - "4200:4000" # HTTP port mapping
      - "7054:5054" # Metrics port mapping
    depends_on:
      - geth-3
    restart: unless-stopped


